/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Список предстоящих встреч всех типов событий в одном списке.
         *
         *     По умолчанию возвращает бронирования с startAt >= now(), отсортированные по startAt asc.
         *     Параметр from позволяет задать нижнюю границу фильтрации.
         */
        get: operations["AdminBookings_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список всех типов событий владельца. */
        get: operations["AdminEventTypes_list"];
        put?: never;
        /** @description Создаёт новый тип события. Возвращает 409, если id уже занят. */
        post: operations["AdminEventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types/{eventTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Возвращает тип события по идентификатору. */
        get: operations["AdminEventTypes_get"];
        put?: never;
        post?: never;
        /** @description Удаляет тип события. */
        delete: operations["AdminEventTypes_delete"];
        options?: never;
        head?: never;
        /** @description Частично обновляет тип события. */
        patch: operations["AdminEventTypes_update"];
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Создаёт бронирование на выбранный слот.
         *
         *     endAt вычисляется как startAt + durationMinutes типа события.
         *     startAt должен попадать в окно записи (14 дней от текущей даты).
         *     Возвращает 409, если интервал пересекается с существующим бронированием любого типа.
         */
        post: operations["PublicBookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список типов событий для страницы выбора вида брони. */
        get: operations["PublicEventTypes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{eventTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Детали типа события по идентификатору. */
        get: operations["PublicEventTypes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{eventTypeId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Свободные слоты для выбранного типа события.
         *
         *     Окно записи по умолчанию: 14 дней от текущей даты.
         *     Параметры from/to позволяют сузить диапазон внутри этого окна.
         *     В ответе возвращаются только слоты с available=true.
         *     Слоты генерируются по рабочим часам 09:00–18:00 UTC с шагом durationMinutes.
         *     На одно время нельзя создать две записи, даже разных типов событий.
         */
        get: operations["PublicEventTypes_listSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Возвращает профиль единственного владельца календаря. */
        get: operations["OwnerResource_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Бронирование встречи гостем. */
        Booking: {
            id: string;
            eventTypeId: string;
            eventTypeTitle: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            guestName: string;
            guestEmail: string;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Список бронирований для админской страницы. */
        BookingList: {
            items: components["schemas"]["Booking"][];
        };
        /** @description Конфликт: слот уже занят или идентификатор типа события уже существует. */
        ConflictError: components["schemas"]["ProblemDetails"];
        /** @description Данные для создания бронирования. */
        CreateBookingRequest: {
            eventTypeId: string;
            /** Format: date-time */
            startAt: string;
            guestName: string;
            guestEmail: string;
        };
        /** @description Данные для создания типа события. */
        CreateEventTypeRequest: {
            id: string;
            title: string;
            description: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /** @description Тип события, доступный для бронирования. */
        EventType: {
            id: string;
            title: string;
            description: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /** @description Ресурс не найден. */
        NotFoundError: components["schemas"]["ProblemDetails"];
        /** @description Единственный заранее заданный владелец календаря. */
        Owner: {
            /**
             * @description Фиксированный идентификатор единственного владельца.
             * @enum {string}
             */
            id: "default";
            displayName: string;
        };
        ProblemDetails: {
            code: string;
            message: string;
        };
        /** @description Вычисляемый временной слот для бронирования. */
        Slot: {
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            /** @description true, если слот свободен и попадает в окно записи. */
            available: boolean;
        };
        /** @description Список слотов с границами окна записи. */
        SlotsResponse: {
            /**
             * Format: date
             * @description Окно записи: 14 дней от текущей даты.
             */
            windowStart: string;
            /** Format: date */
            windowEnd: string;
            items: components["schemas"]["Slot"][];
        };
        /** @description Данные для частичного обновления типа события. */
        UpdateEventTypeRequest: {
            title?: string;
            description?: string;
            /** Format: int32 */
            durationMinutes?: number;
        };
        /** @description Запрос содержит некорректные данные или слот вне окна записи (14 дней). */
        ValidationError: components["schemas"]["ProblemDetails"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminBookings_list: {
        parameters: {
            query?: {
                /** @description Нижняя граница startAt (по умолчанию — текущее время). */
                from?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingList"];
                };
            };
        };
    };
    AdminEventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    AdminEventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventTypeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Конфликт: слот уже занят или идентификатор типа события уже существует. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
        };
    };
    AdminEventTypes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    AdminEventTypes_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    AdminEventTypes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventTypeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    PublicBookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Запрос содержит некорректные данные или слот вне окна записи (14 дней). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description Ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description Конфликт: слот уже занят или идентификатор типа события уже существует. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
        };
    };
    PublicEventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    PublicEventTypes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    PublicEventTypes_listSlots: {
        parameters: {
            query?: {
                /** @description Начало диапазона (по умолчанию — текущая дата). */
                from?: string;
                /** @description Конец диапазона (по умолчанию — текущая дата + 14 дней). */
                to?: string;
            };
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotsResponse"];
                };
            };
            /** @description Ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    OwnerResource_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Owner"];
                };
            };
        };
    };
}
